### ISSUE TITLE
AGP Version of Gradle Plugin

### ISSUE THREAD

**Issue by iononi** [facingii/TYAM-2022#2]
Al construir el proyecto me salta el siguiente error:
![AGP version error](https://user-images.githubusercontent.com/90079777/193160191-ae7f42bd-3102-4841-87db-cf3ca73542d4.png)

Al cambiar la versión del AGP del 7.3.0 al 7.2.2 se corrige el problema:
![image](https://user-images.githubusercontent.com/90079777/193160441-95154f6d-992f-44bb-a8c1-14b599b39378.png)

El error se presentó en la siguiente versión de Android Studio (para Windows).
![Android Studio version](https://user-images.githubusercontent.com/90079777/193173192-63a32de6-1dd5-44b3-97ae-a0dc131d165f.png)

No sé si a los demás les pase los mismo, por si acaso, aquí dejo la solución.

@gonzososa @facingii

**Comment by facingii** [comment]
Gracias por el apunte. Algo similar le pasó a Oscar García y lo corrigió igualmente bajando a la versión soportada por su IDE. Cierro este issue y dejo tu contribución en el wiki.

**Comment by iononi** [comment]
> Gracias por el apunte. Algo similar le pasó a Oscar García y lo corrigió igualmente bajando a la versión soportada por su IDE. Cierro este issue y dejo tu contribución en el wiki.

Creo que se debe a que hay una nueva versión disponible de Android Studio. Anteriormente era la Chipmunk y la nueva es la Dolphin. Acabo de hacer la actualización y ya puedo actualizar el AGP a la versión 7.3.0. Saludos!
